GestorP/urls.py
from django.contrib import admin
from django.conf.urls import url
from django.conf.urls import include
from django.urls import path # new para el logout
from django.contrib import auth

from django.conf import settings
from django.conf.urls.static import static

import menu

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')), # new para el logout
    url(r'^usuario/', include('usuario.urls')),
    url(r'^proyecto/', include('proyecto.urls')),
    url(r'^rol/', include('Rol.urls')),
    url(r'^menu/', include('menu.urls')),
    url(r'^$', menu.views.index),
    url(r'^team/', include('team.urls')),
    url(r'^us/', include('us.urls')),
    url(r'^tablero/', include('tablero.urls')),
    url(r'^sprint/', include('sprint.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sprint/urls.py
from django.conf.urls import url
from . import views

"""
Lista de URLs de Sprints
"""

urlpatterns = [
    url(r'^iniciar/(?P<proyecto_id>[0-9]+)/$', views.iniciar),
    url(r'^iniciar2/(?P<proyecto_id>[0-9]+)/$', views.iniciar2),
    url(r'^horas/(?P<teammember_id>[0-9]+)/(?P<proyecto_id>[0-9]+)/$', views.horas_disponibles),
    url(r'^finalizar/(?P<sprint_id>[0-9]+)/$', views.finalizar),
    url(r'^reunion/(?P<sprint_id>[0-9]+)/$', views.addReunion),
    url(r'^ver_reuniones/(?P<sprint_id>[0-9]+)/$', views.verReuniones),
    url(r'^control_calidad/(?P<sprint_id>[0-9]+)/$', views.control_calidad),
    url(r'^control_calidad_mover/(?P<sprint_id>[0-9]+)/$', views.control_calidad_mover),
    url(r'^elegir_para_importar/(?P<sprint_destino>[0-9]+)/$', views.elegir_para_importar),
    url(r'^importar/(?P<sprint_origen>[0-9]+)/(?P<sprint_destino>[0-9]+)/$', views.importar_sprint),
    url(r'^sprints_anteriores/(?P<id_proyecto>[0-9]+)', views.sprints_anteriores, name='sprints_anteriores'),
]

us/urls.py
from django.urls import path, re_path


from django.conf.urls import include, url
from . import views

"""
Lista de URLs de User Stories
"""

urlpatterns = [
    url(r'^(?P<pk>[0-9]+)', views.product_backlog, name='p_b'),
    url(r'^elegir/(?P<pk>[0-9]+)', views.product_backlog_para_elegir, name='p_b2'),
    url(r'^sprint/(?P<pk>[0-9]+)', views.sprint_backlog_para_elegir, name='s_b'),
    url(r'^sprintb/(?P<pk>[0-9]+)', views.sprint_backlog, name='s_b2'),
    url(r'^finalizados/(?P<pk>[0-9]+)', views.finalizados, name='finalizados'),
    url(r'^crear/(?P<pk>[0-9]+)', views.crear),
    url(r'^crear2/(?P<pk>[0-9]+)', views.crear2),
    url(r'^add/(?P<pk>[0-9]+)', views.add_tablero),
    url(r'^modificar/(?P<pk>[0-9]+)', views.modificar),
    url(r'^eliminar/(?P<pk>[0-9]+)', views.eliminar),
    url(r'^avanzar/(?P<pk>[0-9]+)', views.avanzar),
    url(r'^retroceder/(?P<pk>[0-9]+)', views.retroceder),
    url(r'^adjuntar/(?P<pk>[0-9]+)', views.adjuntar, name='adjuntar'),
    url(r'^buscarus/(?P<pk>[0-9]+)', views.buscarus),
    url(r'^a_sprint/(?P<proyecto_id>[0-9]+)/(?P<us_id>[0-9]+)', views.a_sprint),
    url(r'^a_product/(?P<proyecto_id>[0-9]+)/(?P<us_id>[0-9]+)', views.a_product),
    
   re_path(r'^daily/(?P<us_id>[0-9]+)/(?P<adelante>[0-1]+)', views.addDaily, name='cambio_estado'),

   #url(r'^daily/(?P<us_id>[0-9]+)/(?P<adelante>[0-1]+)', views.addDaily, name='cambio_estado'),
    url(r'^listar_archivos_notas/(?P<us_id>[0-9]+)', views.listar_archivos_notas),
    url(r'^calidad/(?P<us_id>[0-9]+)', views.calidad),
    url(r'^calidad_listo/(?P<us_id>[0-9]+)', views.calidad_listo),
    url(r'^horas/(?P<us_id>[0-9]+)', views.horas),
    url(r'^reportebacklog/(?P<id_proyecto>[0-9]+)', views.reportebacklog),
    url(r'^reporteprioridad/(?P<pk>[0-9]+)', views.reporteprioridad),
    url(r'^horasreales/(?P<pk>[0-9]+)', views.horasreales),
    url(r'^reportesprint/(?P<pk>[0-9]+)', views.reportesprint),
    url(r'^reportesprint2/(?P<pk>[0-9]+)', views.reportesprint2),

]

sprint/models.py
from django.db import models

# Create your models here.
from django.db.models import PROTECT

from proyecto.models import Proyecto
from team.models import TeamMember

ESTADOS = (
    ('ACT', 'Activo'), # cuando se inicia
    ('TER', 'Terminado'), # cuando se termina
)

class Sprint(models.Model):
    """
    Modelo de la clase Sprint
    """
    estado = models.CharField(max_length=3, choices=ESTADOS, default='ACT')
    proyecto = models.ForeignKey(Proyecto, on_delete=PROTECT, null=True, blank=True)
    fecha_ini = models.DateField(verbose_name='fecha de inicio', null=True, blank=True)
    fecha_fin = models.DateField(verbose_name='fecha de finalizacion', null=True, blank=True)
    fecha_fin_est = models.DateField(verbose_name='fecha de finalizacion estimada', null=True, blank=True)
    team_sprint = models.ManyToManyField(TeamMember, through='Horas')
    para_importar = models.TextField(null=True, blank=True)

class Horas(models.Model):
    """
    Modelo de la clase Horas, la cual es una relación entre el Sprint
    y un Teammember que pertenece al Proyecto del Sprint.
    Almacena las horas que debera el usuario por Sprint.
    """
    sprint = models.ForeignKey(Sprint, on_delete=models.CASCADE)
    teammember = models.ForeignKey(TeamMember, on_delete=models.CASCADE)
    horas_trabajadas = models.IntegerField(default=0)

    def __str__(self):
        return self.teammember.id_usuario.user.username
class Reunion(models.Model):
    """
    Modelo de la clase Reuniones Retrospectivas: notas añadidas a cada Sprint
    """
    reunion = models.TextField()
    sprint = models.OneToOneField(Sprint, null=True, blank=True, on_delete=PROTECT)
    class Meta:
        verbose_name_plural = "Reuniones"

    def __str__(self):
        return self.reunion

sprint/forms.py
from django import forms
from .models import Sprint, Reunion, Horas

class IniciarSprintForm(forms.ModelForm):
    """
    Formulario para la creación de un nuevo Sprint
    """
    class Meta:
        model = Sprint
        fields = ('fecha_fin_est',)


class ReunionForm(forms.ModelForm):
    """
    Formulario para la creación de Reuniones
    """
    class Meta:
        model = Reunion
        fields = ('reunion',)

sprint/views.py
from django.contrib.auth.decorators import login_required
from django.db import transaction
from django.db.models import Q
from django.http import HttpResponseForbidden
from django.shortcuts import render, redirect
from django.contrib import messages
from datetime import date, datetime

# Create your views here.
import proyecto
import sprint
from proyecto.models import Proyecto
from sprint.forms import IniciarSprintForm, ReunionForm
from sprint.models import Sprint, Reunion, Horas
from tablero.models import Tablero, Fase
from team.models import TeamMember, Team
from us.models import Us
from usuario.models import Usuario

@login_required
@transaction.atomic
def iniciar(request, proyecto_id):
    """
    Vista para iniciar un Sprint. Se selecciona la fecha de finalización estimada,
    los teammembers del proyecto que van a formar parte del Team de Sprint, con
    la cantidad de horas que cada teammember va a dedicar a el Sprint.
    :param request:
    :param proyecto_id: id del proyecto dentro del cual se iniciara el sprint
    """
    usuarios = TeamMember.objects.filter(team__id_proyecto=proyecto_id)
    usuarios = list(usuarios)
    proyecto = Proyecto.objects.get(id = proyecto_id)

    teammember = TeamMember.objects.filter(id_usuario=request.user.usuario.id)
    teammember = list(teammember)
    permitido = False
    is_scrum = False
    us_proyecto = []
    rol_usuario = []
    try:
        for i in range(len(teammember)):
            try:
                team = Team.objects.get(id_team_member=teammember[i].id)
            except:
                continue
            if team.id_proyecto_id == proyecto.id:
                if teammember[i].id_rol.nombre == 'scrum':
                    is_scrum = True
                    permitido = True
    except:
        return HttpResponseForbidden()
    if permitido:
        if request.method == 'POST' and 'iniciar' in request.POST:
            form = IniciarSprintForm(request.POST)
            teammem_seleccionados = request.POST.getlist('checks[]')
            if len(teammem_seleccionados) == 0:
                messages.error(request,
                               'Seleccione al menos un Team Member para el Sprint.')
                return redirect('/sprint/iniciar/' + str(proyecto_id))
            if form.is_valid():
                obj = form.save(commit=False)
                if obj.fecha_fin_est == None:
                    messages.error(request, 'Campo Fecha de Finalización Estimada es obligatorio.')
                    return redirect('/sprint/iniciar/' + str(proyecto_id))
                if obj.fecha_fin_est < date.today():
                    messages.error(request, 'La fecha de finaización estimada debe ser mayor o igual a la fecha de inicio (hoy)')
                    return redirect('/sprint/iniciar/' + str(proyecto_id))
                obj.proyecto = Proyecto.objects.get(id=proyecto_id)
                obj.fecha_ini = date.today()
                obj.save()
                i=0
                for tm in teammem_seleccionados:
                    aux='cantidad'+tm
                    hs_trab = request.POST[aux]

                    hs = Horas.objects.create(sprint=obj, teammember=TeamMember.objects.get(id=tm),horas_trabajadas=hs_trab)
                    hs.save()
                    i=i+1
                messages.success(request, ('Se inició correctamente el Sprint.'))
                return redirect('/sprint/iniciar2/'+str(proyecto_id))
        elif request.method == 'POST' and 'importar' in request.POST:
            form = IniciarSprintForm(request.POST)
            teammem_seleccionados = request.POST.getlist('checks[]')
            if len(teammem_seleccionados) == 0:
                messages.error(request,
                               'Seleccione al menos un Team Member para el Sprint.')
                return redirect('/sprint/iniciar/' + str(proyecto_id))
            if form.is_valid():
                obj = form.save(commit=False)
                if obj.fecha_fin_est == None:
                    messages.error(request, 'Campo Fecha de Finalización Estimada es obligatorio.')
                    return redirect('/sprint/iniciar/' + str(proyecto_id))
                if obj.fecha_fin_est < date.today():
                    messages.error(request,
                                   'La fecha de finaización estimada debe ser mayor o igual a la fecha de inicio (hoy)')
                    return redirect('/sprint/iniciar/' + str(proyecto_id))
                obj.proyecto = Proyecto.objects.get(id=proyecto_id)
                obj.fecha_ini = date.today()

                obj.save()
                i = 0
                for tm in teammem_seleccionados:
                    aux = 'cantidad' + tm
                    hs_trab = request.POST[aux]

                    hs = Horas.objects.create(sprint=obj, teammember=TeamMember.objects.get(id=tm),
                                              horas_trabajadas=hs_trab)
                    hs.save()
                    i = i + 1
                messages.success(request, ('Se inició correctamente el Sprint.'))
                return redirect('/sprint/elegir_para_importar/' + str(obj.id))
        else:
            form = IniciarSprintForm()
        return render(request,'sprint/iniciar.html',{'form':form ,'usuarios':usuarios, 'proyecto':proyecto})
    else:
        return HttpResponseForbidden()

def iniciar2(request, proyecto_id):
    """
        Vista para la segunda pagina de inicio de Sprint
        :param request:
        :param proyecto_id: id del proyecto dentro del cual se iniciara el spri
    """
    proyecto = Proyecto.objects.get(id=proyecto_id)

    teammember = TeamMember.objects.filter(id_usuario=request.user.usuario.id)
    teammember = list(teammember)
    permitido = False
    is_scrum = False
    us_proyecto = []
    rol_usuario = []
    try:
        for i in range(len(teammember)):
            try:
                team = Team.objects.get(id_team_member=teammember[i].id)
            except:
                continue
            if team.id_proyecto_id == proyecto.id:
                if teammember[i].id_rol.nombre == 'scrum':
                    is_scrum = True
                    permitido = True
    except:
        return HttpResponseForbidden()
    if permitido:

        sprint = Sprint.objects.get(proyecto=proyecto,estado='ACT')
        uss = Us.objects.filter(proyecto=proyecto, sprint=sprint)
        uss = list(uss)
        long = len(uss)
        return render(request,'sprint/iniciar_2.html',{'proyecto':proyecto, 'long':long})
    else:
        return HttpResponseForbidden()

@login_required
@transaction.atomic
def horas_disponibles(request, teammember_id, proyecto_id):
    """
    Vista en la que se calculan las horas disponibles para un usuario del sprint
    :param request:
    :param teammember_id: id del team member del cual se quiere verificar las horas
    :param proyecto_id: id del proyecto dentro del cual se iniciara el sprint
    """
    teammember = TeamMember.objects.get(id = teammember_id)
    proyecto = Proyecto.objects.get(id = proyecto_id)

    usuario = teammember.id_usuario
    horas_ocupadas = Horas.objects.filter(sprint__estado='ACT',teammember__id_usuario=usuario)
    horas_ocupadas = list(horas_ocupadas)
    horas_laborales = usuario.horas_laborales
    disponibles = horas_laborales
    for hora in horas_ocupadas:
        disponibles = disponibles - hora.horas_trabajadas
    mensaje = ''
    if (disponibles > 0):
        mensaje = 'Tiene ' + str(disponibles) + ' horas disponibles.'
    elif (disponibles < 0):
        mensaje = 'El usuario ya trabaja ' + str(disponibles * -1) + ' más de las que tiene disponible'
    else:
        mensaje = 'El usuario ya trabaja exactamente todas sus horas laborales diarias.'
    return render(request,'sprint/horas_disponibles.html',{'mensaje':mensaje, 'proyecto':proyecto})

@login_required
@transaction.atomic
def addReunion(request, sprint_id):
    """
    Vista en la cual se añade una Reunion retrospectiva a un sprint
    :param request:
    :param sprint_id: id del sprint al cual se añadira la reunion
    """
    sprint = Sprint.objects.get(id=sprint_id)
    proyecto = Proyecto.objects.get(sprint=sprint)

    teammember = TeamMember.objects.filter(id_usuario=request.user.usuario.id)
    teammember = list(teammember)
    permitido = False
    is_scrum = False
    us_proyecto = []
    rol_usuario = []
    try:
        for i in range(len(teammember)):
            try:
                team = Team.objects.get(id_team_member=teammember[i].id)
            except:
                continue
            if team.id_proyecto_id == proyecto.id:
                if teammember[i].id_rol.nombre == 'scrum':
                    is_scrum = True
                    permitido = True
    except:
        return HttpResponseForbidden()
    if permitido:

        if request.method == "POST":
            form = ReunionForm()
            reunion = request.POST['reunion']
            if reunion is not "":
                obj = form.save(commit=False)
                obj.reunion = reunion
                obj.sprint = sprint
                obj.save()
                messages.success(request, ('Se adjuntó correctamente la reunión retrospectiva'))
                return redirect('/sprint/consultar/'+str(sprint_id))
        else:
            form = ReunionForm()
        return render(request,'sprint/reunion.html',{'form':form})
    else:
        return HttpResponseForbidden()

@login_required
@transaction.atomic
def verReuniones(request,sprint_id):
    """
    Vista en la que se visualizan las reuniones de un sprint
    :param request:
    :param sprint_id: id del sprint del cual se quieren ver las reuniones
    """
    sprint = Sprint.objects.get(id=sprint_id)
    reuniones = Reunion.objects.filter(sprint=sprint)
    return render(request,'sprint/ver_reuniones.html',{'reuniones':reuniones})

@login_required
@transaction.atomic
def finalizar(request, sprint_id):
    """

templates/sprint/control_calidad.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}Control de Calidad{% endblock title %}

{% block content %}
<div class="jumbotron">

        <script>
                function myFunction(id, mostrar) {
                    var x = document.getElementById(id);
                    if (x.style.display === "none") {
                        x.style.display = "block";
                    } else {
                        x.style.display = "none";
                    }
                    var y= document.getElementById(mostrar);
                    if(y.innerText=='ocultar'){
                        y.innerText='mostrar';
                    }else{
                        y.innerText='ocultar';
                    }
                }
                </script>
                <script>
                  function resizeIframe(obj) {
                    obj.style.height = obj.contentWindow.document.body.scrollHeight + 20 + 'px';
                  }
                </script>
                <style>
                    {% for us in uss %}
                        #cambiar{{ us.id }}{
                            font-size: small;
                        }
                    {% endfor %}
                    </style>
                
                <h2 class="text-danger" align="center">Realizar Control de Calidad</h2>
                
                <form method="POST" action="">
                {% csrf_token %}
                
                {% if uss %}
                {% for us in uss %}
                    <h3 class="text-dark">{{ us }}<a style="padding-left: 2px;" id="cambiar{{ us.id }}" href="#" onclick="myFunction('control{{ us.id }}','cambiar')">mostrar/ocultar</a></h3>
                    <a id ="control{{ us.id }}">
                   <div style="padding-left: 8px;"> <b>Tipo de User Story: </b>{{ us.tablero }} del proyecto <i>{{ us.proyecto }}</i><br>
                    <b>Descripción Breve: </b>{{ us.descripcion_breve }}<br>
                    <b>Descripción Completa: </b>{{ us.descripcion_completa }}<br>
                    <span title="Prioridad: {{ us.prioridad }}
                Valor Técnico: {{ us.valor_tecnico }}
                Valor de Negocio: {{ us.valor_negocio }}"><b>Prioridad Promedio: </b>{{ us.prioridad_promedio }}</span><br>
                    <b>Usuario: </b>{{ us.usuario }}<br>
                       </div>
                    <iframe width="100%" src="/us/listar_archivos_notas/{{ us.id }}" frameborder="0" scrolling="no" onload="resizeIframe(this);reload()"></iframe>
                    <b style="padding-left: 8px">Tiempo de Finalización Estimado: </b>{{ us.tiempo_finalizacion }}<br>
                
                
                
                <div style="padding-left: 8px">
                <br>¿Desea Aprobar el US?<br>
                <input type="radio" checked name="checks{{ us.id }}[]" value="si">Aprobar<br>
                <input type="radio" checked name="checks{{ us.id }}[]" value="no">No Aprobar<br>
                    <br>
                
                </div>
                
                    
                    {% endfor %}
                {% else %}
                    <b>No hay User Stories para Control de Calidad</b>
                {% endif %}
                <div align="center">
                    {% if uss %}
                    <input type="submit" class="btn btn-success" value="Aceptar" />
                    {% else %}
                    <a class="btn btn-warning" href="/sprint/finalizar/{{ sprint.id }}">Finalizar</a>
                    {% endif %}
                    <a class="btn btn-danger" href="/proyecto/trabajo/{{ proyecto.id }}">Cancelar finalización del Sprint</a>
                    </div>
                
                </form>

    
</div>
{% endblock content %}

templates/sprint/control_calidad_mover.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}SGPA | Control de Calidad{% endblock title %}

{% block content %}
<div class="jumbotron">

    <script>
        function resizeIframe(obj) {
          obj.style.height = obj.contentWindow.document.body.scrollHeight + 20 + 'px';
        }
      </script>
      
      <h2 >Realizar Control de Calidad: </h2>
      
      <form method="POST" action="">
      {% csrf_token %}
      {% if long != 0 %}
          {% for us in uss %}
      <iframe width="100%" src="/us/calidad/{{ us.id }}" frameborder="0" scrolling="no" onload="resizeIframe(this);reload()"></iframe>
      {% endfor %}
      {% else %}
          <b>Aprobó todos los User Stories.</b>
      {% endif %}
      <div align="center">
      <input type="submit" class="btn btn-success" value="Terminar" />
          </div>
      
      </form>

    



</div>
{% endblock content %}

templates/sprint/elegir_para_importar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Elegir Sprint a Importar</title>
</head>
<body>

<h2 style="background-color:#B7F4F2">Importar Sprint</h2>

<i><b>Elija el Sprint a importar...</b></i><br>
<br>
{% for sprint,mensaje in sprints %}
    {% if sprint.para_importar %}
    <a href="/sprint/importar/{{ sprint.id }}/{{ destino.id }}">Del proyecto <i>{{ sprint.proyecto }}</i> {{ mensaje }}</a><br>
    {% endif %}
{% endfor %}
<br>
<a style="font: 13px Arial;
  text-decoration: none;
  background-color: #EEEEEE;
  color: #333333;
  padding: 2px 6px 2px 6px;
  border-top: 1px solid #CCCCCC;
  border-right: 1px solid #333333;
  border-bottom: 1px solid #333333;
  border-left: 1px solid #CCCCCC;" href="/sprint/iniciar2/{{ proyecto.id }}" title="Continuar">No importar</a>
</body>
</html>

templates/sprint/finalizar.html
{% extends 'base.html' %}

{% load crispy_forms_tags %}

{% block title %}SGPA | Finalizar Sprint{% endblock title %}

{% block content %}
<div class="jumbotron">

        <h2 class="text-danger" align="center" >Finalizar Sprint Actual</h2><br>
        <form method="post" action="">
            {% csrf_token %}
            <br>
            <div class="text-center">
            <h3 align="center" class="text-info">¿Desea finalizar el Sprint actual del proyecto "{{ proyecto.nombre }}"?</h3>
                    <br>
            </br>

                <button class="btn btn-success" type="submit">Finalizar</button>
                        <a class="btn btn-danger" href="/proyecto/trabajo/{{ proyecto.id }}" title="Ir la página anterior">Cancelar finalización del Sprint Actual</a>
            </div>

            <br>
            </br>

                        <textarea color:#000 id="reunion" name="reunion" placeholder="Observaciones..." style="height:1px;width:1%;margin-left: 0%;margin-right: 0%; border-bottom-color: rgba(162,158,143,0.39)"></textarea><br>

        </form>


</div>


{% endblock content %}

templates/sprint/horas_disponibles.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Horas Disponibles</title>
</head>
<body>

{{ mensaje }}

</body>
</html>

templates/sprint/importar.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="refresh" content="0; URL=/sprint/iniciar2/{{ proyecto.id }}/">
    <meta name="keywords" content="automatic redirection">
    <title>Importar</title>
</head>
<body>

</body>
</html>

templates/sprint/iniciar.html
{% extends 'base.html' %}

{% block title %}SGPA | Iniciar Sprint{% endblock title %}

{% load crispy_forms_tags %}
{% block content %}
<div class="jumbotron">

        <h2 class="text-danger" align="center">Crear Sprint</h2><br>

        
    
    <div>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <p style="color:#F39C12;"{% if message.tags %} class="{{ message.tags }}"{% endif %} ><i class="fas fa-exclamation-triangle"></i> {{ message }}</p>
        {% endfor %}
    </ul>
    {% endif %}
    </div>




    <form method="POST">
     <div class="form-group">
            {% csrf_token %}
            {{form2}}
        <p><label for="id_fecha_fin_est">Fecha de finalizacion estimada:</label> <input type="text" class="form-control" name="fecha_fin_est" id="id_fecha_fin_est" /></p>
    
    
    {% for usuario in usuarios %}
        {% if usuario.id_rol.nombre != 'owner' %}
        <table class="table table-borderless table-dark">
        <tbody>
            <tr class="bg-info">
                <td >
                    <h4 class="text-white"><input type="checkbox" name="checks[]" value="{{ usuario.id }}"> {{ usuario}}</h4>
                    <input type="number" class="form-control" name="cantidad{{ usuario.id }}" min="1" placeholder="Cantidad en Horas de Trabajo"></p>
                    <div align="left"><iframe frameborder="0" width="95%" height="37px" src="/sprint/horas/{{ usuario.id }}/{{ proyecto.id }}"></iframe></div>
                </td>
            </tr>
        </tbody> 
    </table>
        {% endif %}
    {% endfor %}
    <br>
    <div class="text-right">
        <input class="btn btn-success" type="submit" value="Continuar con Iniciar Sprint" name="iniciar" />
       <!-- <input class="btn btn-info" type="submit" value="Importar Sprint" name="importar" />-->
        <a  class="btn btn-danger" href="/proyecto/trabajo/{{ proyecto.id }}">Cancelar</a>
    </div>
    </div>
    </form>


</div>
{% endblock content %}

templates/sprint/iniciar_2.html
{% extends 'base.html' %}
{% block title %} SGPA | Elegir US{% endblock title %}

{% block content %}
<div class="jumbotron">

    <script>
        function resizeIframe(obj) {
          obj.style.height = obj.contentWindow.document.body.scrollHeight + 20 + 'px';
        }
      </script>
      
      <iframe width="100%" src="/us/elegir/{{ proyecto.id }}" frameborder="0" scrolling="no" onload="resizeIframe(this);reload()"></iframe>
      <iframe width="100%" src="/us/sprint/{{ proyecto.id }}" frameborder="0" scrolling="no" onload="resizeIframe(this);reload()"></iframe>
      {#<iframe width="100%" height="500px" src="/us/sprint/{{ proyecto.id }}" frameborder="0" ></iframe>#}
      <br>
      {% if long != 0 %}
        <div align="center">
        <a href="/proyecto/trabajo/{{ proyecto.id }}" class="btn btn-danger" title="Ir la página anterior">Finalizar</a>
          {% else %}
          <b style="color: red; padding-left: 8px">Debe tener User Stories en su Sprint Backlog para Iniciar el Sprint</b>

          {% endif %}

         <!-- <div class="text-right">

              <a  class="btn btn-danger" href="/proyecto/trabajo/{{ proyecto.id }}">Cancelar</a>
            </div>-->



      </div>
     


</div>

{% endblock content %}

templates/sprint/ver_reuniones.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Ver reuniones</title>
</head>
<body>
Reuniones:<br>
{% for reunion in reuniones %}
    ✰ {{ reunion }} - Fecha de Creación: {{ reunion.fecha }}<br>
{% endfor %}
</body>
</html>